---
title: "Publications"
---

* **Arjun Sondhi**, Alexander S Rich, Siruo Wang, and Jeffrey T Leek (2023). ["Postprediction Inference for Clinical Characteristics Extracted With Machine Learning on Electronic Health Records"](https://ascopubs.org/doi/full/10.1200/CCI.22.00174). Published in *JCO: Clinical Cancer Informatics*. 

* Corey M Benedum, **Arjun Sondhi**, Erin Fidyk, Aaron B Cohen, Sheila Nemeth, Blythe Adamson, Melissa Estévez, and Selen Bozkurt (2023). ["Replication of Real-World Evidence in Oncology Using Electronic Health Record Data Extracted by Machine Learning"](https://www.mdpi.com/2072-6694/15/6/1853). Published in *Cancers*. 

* **Arjun Sondhi**, Janick Weberpals, Chengsheng Jiang, Prakirthi Yerram, Michael Taylor, Meghna Samant, and Sarah T Cherng (2023). ["A systematic approach towards missing lab data in electronic health records: a case study in non-small cell lung cancer and multiple myeloma"](https://ascpt.onlinelibrary.wiley.com/doi/full/10.1002/psp4.12998). Published in *CPT: Pharmacometrics & Systems Pharmacology*. 

* **Arjun Sondhi** (2022). ["Estimating survival parameters under conditionally independent left truncation"](https://onlinelibrary.wiley.com/doi/full/10.1002/pst.2202). Published in *Pharmaceutical Statistics*. [[arxiv]](https://arxiv.org/abs/2107.10911)

* Jean Feng, **Arjun Sondhi**, Jessica Perry, and Noah Simon (2021). ["Selective prediction-set models with coverage guarantees"](https://onlinelibrary.wiley.com/doi/abs/10.1111/biom.13612). Published in *Biometrics*. [[arxiv]](https://arxiv.org/abs/1906.05473)

* **Arjun Sondhi**, Brian Segal, Jeremy Snider, Olivier Humblet, and Margaret McCusker (2021). ["Bayesian additional evidence for decision making under small sample uncertainty"](https://link.springer.com/article/10.1186/s12874-021-01432-5). Published in *BMC Medical Research Methodology*.

* David Arbour, Drew Dimmery, and **Arjun Sondhi** (2021). ["Permutation Weighting"](https://proceedings.mlr.press/v139/arbour21a.html). Published in *International Conference on Machine Learning (ICML 2021)*. [[arxiv]](https://arxiv.org/abs/1901.01230)

* **Arjun Sondhi**, David Arbour, and Drew Dimmery (2020). ["Balanced off-policy evaluation in general action spaces"](http://proceedings.mlr.press/v108/sondhi20a.html). Published in *International Conference on Artificial Intelligence and Statistics (AISTATS 2020)*. [[arxiv]](https://arxiv.org/abs/1906.03694)

* **Arjun Sondhi** and Ali Shojaie (2019). ["The Reduced PC-Algorithm: Improved Causal Structure Learning in Large Random Networks"](https://jmlr.org/papers/v20/17-601.html). Published in *Journal of Machine Learning Research*. [[arxiv]](https://arxiv.org/abs/1806.06209)

* **Arjun Sondhi** and Kenneth M. Rice (2017). ["Fast permutation tests and related methods, for association between rare variants and binary outcomes"](https://onlinelibrary.wiley.com/doi/abs/10.1111/ahg.12229). Published in *Annals of Human Genetics*. [[arxiv]](https://arxiv.org/abs/1712.06643)

* **Arjun Sondhi** and Ali Shojaie (2016). ["Causal structure learning with reduced partial correlation thresholding"](https://ieeexplore.ieee.org/abstract/document/7796967). Published in *IEEE Conference on Data Science and Advanced Analytics (DSAA 2016)*.